function t = plots_TC12_lon_5RPE(t, parOEM, Z, U, syekf, sxekf, sxekfstd,...
                                                  syukf, sxukf, sxukfstd,...
                                                  syukfAug, sxukfAug, sxukfAugstd,...
                                                  syrls, sxrls, sxrlsstd,...
                                            tFTR, sxdft, sxdftstd, method);

% Chapter 7: Recursive Parameter Estimation 
% "Flight Vehicle System Identification - A Time Domain Methodology"
% Second Edition
% by Ravindra V. Jategaonkar
% published by AIAA, Reston, VA 20191, USA

XL = t(end) + 5;

% EKF: Plot time histories of measured and estimated observation variables and control inputs
figure(1)
subplot(311),plot(t,Z(:,1), t,syekf(:,1),'r-.');grid;ylabel('{\alpha} (°)');
title('EKF: Time histories of output variables (measured and estimated); input variables')
subplot(312),plot(t,Z(:,2), t,syekf(:,2),'r-.');grid;ylabel('q (°/s)');
subplot(313),plot(t,U(:,1));grid;ylabel('{\delta_e} (°)'); xlabel('Time in sec'); 

% UKF: Plot time histories of measured and estimated observation variables and control inputs
figure(2)
subplot(311),plot(t,Z(:,1), t,syukf(:,1),'r-.');grid;ylabel('{\alpha} (°)');
title('UKF: Time histories of output variables (measured and estimated); input variables')
subplot(312),plot(t,Z(:,2), t,syukf(:,2),'r-.');grid;ylabel('q (°/s)');
subplot(313),plot(t,U(:,1));grid;ylabel('{\delta_e} (°)'); xlabel('Time in sec'); 

% UKF-Augmented: Plot time histories of measured and estimated observation variables and control inputs
figure(3)
subplot(311),plot(t,Z(:,1), t,syukfAug(:,1),'r-.');grid;ylabel('{\alpha} (°)');
title('UKF Augmented: Time histories of output variables (measured and estimated); input variables')
subplot(312),plot(t,Z(:,2), t,syukfAug(:,2),'r-.');grid;ylabel('q (°/s)');
subplot(313),plot(t,U(:,1));grid;ylabel('{\delta_e} (°)'); xlabel('Time in sec'); 

% RLS: Plot time histories of measured and estimated observation variables and control inputs
figure(4)
subplot(311),plot(t,Z(:,1), t,syrls(:,1),'r-.');grid;ylabel('{\alpha} (°)');
title('EFRLS: Time histories of output variables (measured and estimated); input variables')
subplot(312),plot(t,Z(:,2), t,syrls(:,2),'r-.');grid;ylabel('q (°/s)');
subplot(313),plot(t,U(:,1));grid;ylabel('{\delta_e} (°)'); xlabel('Time in sec'); 

% EKF: Plot time histories of estimated parameters
figure(5)
subplot(811),plot(t,sxekf(:,3),'k', t,sxekf(:,3)+sxekfstd(:,3),'r',...
                                    t,sxekf(:,3)-sxekfstd(:,3),'r',...
                                    [0 XL],[parOEM(1,1) parOEM(1,1)]);grid;ylabel('Z_0');
title('EKF: Convergence of parameter estimates with error bounds')
subplot(812),plot(t,sxekf(:,4),'k', t,sxekf(:,4)+sxekfstd(:,4),'r',...
                                    t,sxekf(:,4)-sxekfstd(:,4),'r',...
                                    [0 XL],[parOEM(1,2) parOEM(1,2)]);grid;ylabel('Z_{\alpha}');
subplot(813),plot(t,sxekf(:,5),'k', t,sxekf(:,5)+sxekfstd(:,5),'r',...
                                    t,sxekf(:,5)-sxekfstd(:,5),'r',...
                                    [0 XL],[parOEM(1,3) parOEM(1,3)]);grid;ylabel('Z_q');
subplot(814),plot(t,sxekf(:,6),'k', t,sxekf(:,6)+sxekfstd(:,6),'r',...
                                    t,sxekf(:,6)-sxekfstd(:,6),'r',...
                                    [0 XL],[parOEM(1,4) parOEM(1,4)]);grid;ylabel('Z_{\deltae}');
subplot(815),plot(t,sxekf(:,7),'k', t,sxekf(:,7)+sxekfstd(:,7),'r',...
                                    t,sxekf(:,7)-sxekfstd(:,7),'r',...
                                    [0 XL],[parOEM(1,5) parOEM(1,5)]);grid;ylabel('M_0');
subplot(816),plot(t,sxekf(:,8),'k', t,sxekf(:,8)+sxekfstd(:,8),'r',...
                                    t,sxekf(:,8)-sxekfstd(:,8),'r',...
                                    [0 XL],[parOEM(1,6) parOEM(1,6)]);grid;ylabel('M_{\alpha}');
subplot(817),plot(t,sxekf(:,9),'k', t,sxekf(:,9)+sxekfstd(:,9),'r',...
                                    t,sxekf(:,9)-sxekfstd(:,9),'r',...
                                    [0 XL],[parOEM(1,7) parOEM(1,7)]);grid;ylabel('M_q');
subplot(818),plot(t,sxekf(:,10),'k',t,sxekf(:,10)+sxekfstd(:,10),'r',...
                                    t,sxekf(:,10)-sxekfstd(:,10),'r',...
                                    [0 XL],[parOEM(1,8) parOEM(1,8)]);grid;ylabel('M_{\deltae}');
                                    xlabel('Time in sec');  

% UKF: Plot time histories of estimated parameters
figure(6)
subplot(811),plot(t,sxukf(:,3),'k', t,sxukf(:,3)+sxukfstd(:,3),'r',...
                                    t,sxukf(:,3)-sxukfstd(:,3),'r',...
                                    [0 XL],[parOEM(1,1) parOEM(1,1)]);grid;ylabel('Z_0');
title('UKF: Convergence of parameter estimates with error bounds')
subplot(812),plot(t,sxukf(:,4),'k', t,sxukf(:,4)+sxukfstd(:,4),'r',...
                                    t,sxukf(:,4)-sxukfstd(:,4),'r',...
                                    [0 XL],[parOEM(1,2) parOEM(1,2)]);grid;ylabel('Z_{\alpha}');
subplot(813),plot(t,sxukf(:,5),'k', t,sxukf(:,5)+sxukfstd(:,5),'r',...
                                    t,sxukf(:,5)-sxukfstd(:,5),'r',...
                                    [0 XL],[parOEM(1,3) parOEM(1,3)]);grid;ylabel('Z_q');
subplot(814),plot(t,sxukf(:,6),'k', t,sxukf(:,6)+sxukfstd(:,6),'r',...
                                    t,sxukf(:,6)-sxukfstd(:,6),'r',...
                                    [0 XL],[parOEM(1,4) parOEM(1,4)]);grid;ylabel('Z_{\deltae}');
subplot(815),plot(t,sxukf(:,7),'k', t,sxukf(:,7)+sxukfstd(:,7),'r',...
                                    t,sxukf(:,7)-sxukfstd(:,7),'r',...
                                    [0 XL],[parOEM(1,5) parOEM(1,5)]);grid;ylabel('M_0');
subplot(816),plot(t,sxukf(:,8),'k', t,sxukf(:,8)+sxukfstd(:,8),'r',...
                                    t,sxukf(:,8)-sxukfstd(:,8),'r',...
                                    [0 XL],[parOEM(1,6) parOEM(1,6)]);grid;ylabel('M_{\alpha}');
subplot(817),plot(t,sxukf(:,9),'k', t,sxukf(:,9)+sxukfstd(:,9),'r',...
                                    t,sxukf(:,9)-sxukfstd(:,9),'r',...
                                    [0 XL],[parOEM(1,7) parOEM(1,7)]);grid;ylabel('M_q');
subplot(818),plot(t,sxukf(:,10),'k',t,sxukf(:,10)+sxukfstd(:,10),'r',...
                                    t,sxukf(:,10)-sxukfstd(:,10),'r',...
                                    [0 XL],[parOEM(1,8) parOEM(1,8)]);grid;ylabel('M_{\deltae}');
                                    xlabel('Time in sec');  

% UKF-Augmented: Plot time histories of estimated parameters
figure(7)
subplot(811),plot(t,sxukfAug(:,3),'k', t,sxukfAug(:,3)+sxukfAugstd(:,3),'r',...
                                    t,sxukfAug(:,3)-sxukfAugstd(:,3),'r',...
                                    [0 XL],[parOEM(1,1) parOEM(1,1)]);grid;ylabel('Z_0');
title('UKF Augmented: Convergence of parameter estimates with error bounds')
subplot(812),plot(t,sxukfAug(:,4),'k', t,sxukfAug(:,4)+sxukfAugstd(:,4),'r',...
                                    t,sxukfAug(:,4)-sxukfAugstd(:,4),'r',...
                                    [0 XL],[parOEM(1,2) parOEM(1,2)]);grid;ylabel('Z_{\alpha}');
subplot(813),plot(t,sxukfAug(:,5),'k', t,sxukfAug(:,5)+sxukfAugstd(:,5),'r',...
                                    t,sxukfAug(:,5)-sxukfAugstd(:,5),'r',...
                                    [0 XL],[parOEM(1,3) parOEM(1,3)]);grid;ylabel('Z_q');
subplot(814),plot(t,sxukfAug(:,6),'k', t,sxukfAug(:,6)+sxukfAugstd(:,6),'r',...
                                    t,sxukfAug(:,6)-sxukfAugstd(:,6),'r',...
                                    [0 XL],[parOEM(1,4) parOEM(1,4)]);grid;ylabel('Z_{\deltae}');
subplot(815),plot(t,sxukfAug(:,7),'k', t,sxukfAug(:,7)+sxukfAugstd(:,7),'r',...
                                    t,sxukfAug(:,7)-sxukfAugstd(:,7),'r',...
                                    [0 XL],[parOEM(1,5) parOEM(1,5)]);grid;ylabel('M_0');
subplot(816),plot(t,sxukfAug(:,8),'k', t,sxukfAug(:,8)+sxukfAugstd(:,8),'r',...
                                    t,sxukfAug(:,8)-sxukfAugstd(:,8),'r',...
                                    [0 XL],[parOEM(1,6) parOEM(1,6)]);grid;ylabel('M_{\alpha}');
subplot(817),plot(t,sxukfAug(:,9),'k', t,sxukfAug(:,9)+sxukfAugstd(:,9),'r',...
                                    t,sxukfAug(:,9)-sxukfAugstd(:,9),'r',...
                                    [0 XL],[parOEM(1,7) parOEM(1,7)]);grid;ylabel('M_q');
subplot(818),plot(t,sxukfAug(:,10),'k',t,sxukfAug(:,10)+sxukfAugstd(:,10),'r',...
                                    t,sxukfAug(:,10)-sxukfAugstd(:,10),'r',...
                                    [0 XL],[parOEM(1,8) parOEM(1,8)]);grid;ylabel('M_{\deltae}');
                                    xlabel('Time in sec');  

% Plot time histories of estimated parameters (EKF, UKF, UKFaug, EFRLS, FTR)
figure(8)
subplot(321),plot(t,sxekf(:,4),'b', t,sxukf(:,4),'r', t,sxukfAug(:,4),'c',...
                  tFTR,sxdft(:,1),'m', t,sxrls(:,4),'k',...
                  [0 XL],[parOEM(1,2) parOEM(1,2)]);...
                  axis([0 XL,-2 2]);grid;...
                  legend('Z_{\alpha} EKF','     UKF','     UKFaug','     FTR','     EFRLS','     MLE',1);
title('EKF, UKF, UKFaug, EFRLS, FTR: Convergence of parameter estimates')
subplot(323),plot(t,sxekf(:,5),'b', t,sxukf(:,5),'r', t,sxukfAug(:,5),'c',...
                  tFTR,sxdft(:,2)-1,'m',t,sxrls(:,5),'k',...
                  [0 XL],[parOEM(1,3) parOEM(1,3)]);...
                  axis([0 XL,-2 2]);grid;...
                  legend('Z_q EKF','     UKF','     UKFaug','     FTR','     EFRLS','     MLE',1);
subplot(325),plot(t,sxekf(:,6),'b', t,sxukf(:,6),'r', t,sxukfAug(:,6),'c',...
                  tFTR,sxdft(:,3),'m',t,sxrls(:,6),'k',...
                  [0 XL],[parOEM(1,4) parOEM(1,4)]);...
                  axis([0 XL,-2 6]);grid;...
                  legend('Z_{\deltae} EKF','     UKF','       UKFaug','      FTR','      EFRLS','      MLE',1);
                  xlabel('Time in sec')
subplot(322),plot(t,sxekf(:,8),'b', t,sxukf(:,8),'r', t,sxukfAug(:,8),'c',...
                  tFTR,sxdft(:,4),'m',t,sxrls(:,8),'k',...
                  [0 XL],[parOEM(1,6) parOEM(1,6)]);...
                  axis([0 XL, -10 0]);grid;...
                  legend('M_{\alpha} EKF','     UKF','     UKFaug','     FTR','     EFRLS','     MLE',1);
subplot(324),plot(t,sxekf(:,9),'b', t,sxukf(:,9),'r', t,sxukfAug(:,9),'c',...
                  tFTR,sxdft(:,5),'m',t,sxrls(:,9),'k',...
                  [0 XL],[parOEM(1,7) parOEM(1,7)]);...
                  axis([0 XL,-5 0]);grid;...
                  legend('M_q EKF','     UKF','     UKFaug','     FTR','     EFRLS','     MLE',1);
subplot(326),plot(t,sxekf(:,10),'b', t,sxukf(:,10),'r', t,sxukfAug(:,10),'c',...
                  tFTR,sxdft(:,6),'m',t,sxrls(:,10),'k',...
                  [0 XL],[parOEM(1,8) parOEM(1,8)]);...
                  axis([0 XL,-10 0]);grid;...
                  legend('M_{\deltae} EKF','       UKF','       UKFaug','       FTR','       EFRLS','       MLE',1);
                  xlabel('Time in sec')
