function [fdata_sid,varlab] = compfmc(fdata,cbar,bspan,sarea)
%
%  function [fdata_sid,varlab] = compfmc(fdata,cbar,bspan,sarea)
%
%  Usage: [fdata_sid,varlab] = compfmc(fdata,cbar,bspan,sarea);
%
%  Description:
%
%    Computes the non-dimensional aerodynamic force coefficients 
%    and non-dimensional angular rates based
%    on measured flight data from input array fdata.
%    Outputs are stored in standard data array channels
%    in output fdata_sid.  Inputs cbar, bspan, and sarea can 
%    be omitted if fdata contains this information.  
%
%  Input:
%    
%    fdata = flight test data array in standard configuration.
%     cbar = wing mean aerodynamic chord, ft.
%    bspan = wing span, ft.
%    sarea = wing area, ft.
%
%  Output:
%
%  fdata_sid = flight test data array in SIDPAC standard configuration.
%     varlab = standard variable labels.
%

%
%    Calls:
%      compfc.m
%      compmc.m
%      ws_mrk_chnl.m
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      19 Feb  2001 - Created and debugged, EAM.
%      12 July 2002 - Made geometry inputs optional, EAM.
%
%  Copyright (C) 2002  Eugene A. Morelli
%
%  This program carries no warranty, not even the implied 
%  warranty of merchantability or fitness for a particular purpose.  
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@larc.nasa.gov
%
[npts,n]=size(fdata);
fdata_sid=fdata;
if nargin < 4
  sarea=fdata(1,77);
end
if nargin < 3
  bspan=fdata(1,78);
end
if nargin < 2
  cbar=fdata(1,79);
end
if ((sarea <=0) | (bspan <= 0) | (cbar <= 0))
  fprintf('\n\n Geometry input error in compfmc.m \n')
  return
end
[CX,CY,CZ,CD,CYw,CL,CT,pv,qv,rv] = compfc(fdata,cbar,bspan,sarea);
fdata_sid(:,[61:63])=[CX,CY,CZ];
fdata_sid(:,[67:70])=[CD,CYw,CL,CT];
[Cl,Cm,Cn] = compmc(fdata,cbar,bspan,sarea);
fdata_sid(:,[64:66])=[Cl,Cm,Cn];
fdata_sid(:,[71:73])=[pv,qv,rv];
%
%  Aircraft geometry.
%
fdata_sid(:,77)=sarea*ones(npts,1);
fdata_sid(:,78)=bspan*ones(npts,1);
fdata_sid(:,79)=cbar*ones(npts,1);
%
%  Default variable labels.
%
varlab=['  time       (sec)     ';...
        '  airspeed   (ft/sec)  ';...
        '  beta       (deg)     ';...
        '  alpha      (deg)     ';...
        '  p          (deg/sec) ';...
        '  q          (deg/sec) ';...
        '  r          (deg/sec) ';...
        '  phi        (deg)     ';...
        '  theta      (deg)     ';...
        '  psi        (deg)     ';...
        '  ax         (g)       ';...
        '  ay         (g)       ';...
        '  az         (g)       ';...
        '  elevator   (deg)     ';...
        '  aileron    (deg)     ';...
        '  rudder     (deg)     ';...
        '  te flap    (deg)     ';...
        '  le flap    (deg)     ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';... 
        '                       ';...
        '                       ';...
        '  qbar       (lbf/ft2) ';...
        '  mach                 ';...
        '  rho        (slug/ft3)';...
        '  altitude   (ft)      ';...
        '  lon stick  (in)      ';...
        '  lat stick  (in)      ';...
        '  rud pedal  (in)      ';...
        '  throttle   (deg)     ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '  thrust     (lbf)     ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '  pdot       (deg/sec2)';...
        '  qdot       (deg/sec2)';...
        '  rdot       (deg/sec2)';...
        '  x cg       (in)      ';...
        '  y cg       (in)      ';...
        '  z cg       (in)      ';...
        '  mass       (slug)    ';...
        '  Ixx        (slug-ft2)';...
        '  Iyy        (slug-ft2)';...
        '  Izz        (slug-ft2)';...
        '  Ixz        (slug-ft2)';...
        '  meas  ax   (g)       ';...
        '  meas  ay   (g)       ';...
        '  meas  az   (g)       ';...
        '  alpdot     (deg/sec) ';...
        '  btadot     (deg/sec) ';...
        '  rtv        (deg)     ';...
        '  ptv        (deg)     ';...
        '  ytv        (deg)     ';...
        '  CX                   ';...
        '  CY                   ';...
        '  CZ                   ';...
        '  Cl                   ';...
        '  Cm                   ';...
        '  Cn                   ';...
        '  CD                   ';...
        '  CYw                  ';...
        '  CL                   ';...
        '  CT                   ';...
        '  phat                 ';...
        '  qhat                 ';...
        '  rhat                 ';...
        '  u          (ft/sec)  ';...
        '  v          (ft/sec)  ';...
        '  w          (ft/sec)  ';...
        '  sarea      (ft2)     ';...
        '  bspan      (ft)      ';...
        '  cbar       (ft)      ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       ';...
        '                       '];
%
%  Mark the channels that have been assigned.
%
for i=1:size(fdata_sid,2),
  if norm(fdata_sid(:,i))~=0
    varlab=ws_mrk_chnl(varlab,i);
  end
end
return
