%
%  Aircraft System Identification Software 
%
%  script sid.m
%
%  Usage: sid
%
%  Description:
%
%    Initializes sid GUI, which is used to run the 
%    System IDentification Programs for AirCraft (SIDPAC).
%
%  Input:
%
%    None
%
%
%  Output:
%
%        fdata = standard data matrix.
%       varlab = standard variable labels.
%      varunit = standard variable units.
%      varname = specific variable names for measured quantities.
%   varconvlab = variable unit conversion labels.
%
%

%
%    Calls:
%      sid_ws.m
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      6 Jan 2000 - Created and debugged, EAM.
%
%  Copyright (C) 2002  Eugene A. Morelli
%
%  This program carries no warranty, not even the implied 
%  warranty of merchantability or fitness for a particular purpose.  
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@larc.nasa.gov
%

%
%  Create default time vector and data matrix.
%
if ~exist('t')
  whos
  t=eval(input('Enter the time variable name ','s'));
  t=t(:,1);
  npts=length(t);
  t=t-t(1);
  dt=1/round(1/(t(2)-t(1)));
  t=[0:dt:(npts-1)*dt]';
end
npts=length(t);
if ~exist('fdata')
  fdata=zeros(length(t),90);
end
if size(fdata,2) < 90
  fdata=[fdata,zeros(npts,90-size(fdata,2))];
end
[npts,nchnls]=size(fdata);
%
%  Get aircraft wing geometry parameters.
%
if ~exist('sarea')
  sarea=input('Enter the wing area in ft2 ');
end
if ~exist('cbar')
  cbar=input('Enter the wing mean aerodynamic chord in ft ');
end
if ~exist('bspan')
  bspan=input('Enter the wing span in ft ');
end
%
%  Default variable labels.
%
if ~exist('varlab')
  varlab=['  time       (sec)     ';...
          '  airspeed   (ft/sec)  ';...
          '  beta       (deg)     ';...
          '  alpha      (deg)     ';...
          '  p          (deg/sec) ';...
          '  q          (deg/sec) ';...
          '  r          (deg/sec) ';...
          '  phi        (deg)     ';...
          '  theta      (deg)     ';...
          '  psi        (deg)     ';...
          '  ax         (g)       ';...
          '  ay         (g)       ';...
          '  az         (g)       ';...
          '  elevator   (deg)     ';...
          '  aileron    (deg)     ';...
          '  rudder     (deg)     ';...
          '  te flap    (deg)     ';...
          '  le flap    (deg)     ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';... 
          '                       ';...
          '                       ';...
          '  qbar       (lbf/ft2) ';...
          '  mach                 ';...
          '  rho        (slug/ft3)';...
          '  altitude   (ft)      ';...
          '  lon stick  (in)      ';...
          '  lat stick  (in)      ';...
          '  rud pedal  (in)      ';...
          '  throttle   (deg)     ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '  thrust     (lbf)     ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '  pdot       (deg/sec2)';...
          '  qdot       (deg/sec2)';...
          '  rdot       (deg/sec2)';...
          '  x cg       (in)      ';...
          '  y cg       (in)      ';...
          '  z cg       (in)      ';...
          '  mass       (slug)    ';...
          '  Ixx        (slug-ft2)';...
          '  Iyy        (slug-ft2)';...
          '  Izz        (slug-ft2)';...
          '  Ixz        (slug-ft2)';...
          '  meas  ax   (g)       ';...
          '  meas  ay   (g)       ';...
          '  meas  az   (g)       ';...
          '  alpdot     (deg/sec) ';...
          '  btadot     (deg/sec) ';...
          '  rtv        (deg)     ';...
          '  ptv        (deg)     ';...
          '  ytv        (deg)     ';...
          '  CX                   ';...
          '  CY                   ';...
          '  CZ                   ';...
          '  Cl                   ';...
          '  Cm                   ';...
          '  Cn                   ';...
          '  CD                   ';...
          '  CYw                  ';...
          '  CL                   ';...
          '  CT                   ';...
          '  phat                 ';...
          '  qhat                 ';...
          '  rhat                 ';...
          '  u          (ft/sec)  ';...
          '  v          (ft/sec)  ';...
          '  w          (ft/sec)  ';...
          '  sarea      (ft2)     ';...
          '  bspan      (ft)      ';...
          '  cbar       (ft)      ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       ';...
          '                       '];
end
%
%  Set up the figure window.
%
sid_ws;
return
