%
%  script sid_cut.m
%
%  Usage: sid_cut;
%
%  Description:
%
%    Creates GUI for cutting the maneuver time from 
%    the standard fdata data matrix.  
%    This routine contains all the code to set up the GUI.  
%
%  Input:
%
%    None
%
%  Output:
%
%    GUI
%
%

%
%    Calls:
%      sid_plot.m
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      11 Jan 2000 - Created and debugged, EAM.
%
%  Copyright (C) 2000  Eugene A. Morelli
%
%  This program carries no warranty, not even the implied 
%  warranty of merchantability or fitness for a particular purpose.  
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@larc.nasa.gov
%

%
%  GUI set up.
%
%
%  Figure window.
%
FgH=figure('Units','normalized',...
           'Position',[0.352 0.0437 0.64 0.88],...
           'Color',[0.8 0.8 0.8],...
           'Name','Aircraft System IDentification',...
           'NumberTitle','off',...
           'Tag','Fig1',...
           'ToolBar','none');
%
%  Axes for plotting.
%
AxH=axes('Box','on',...
         'Units','normalized',...
         'Position',[0.35 0.45 0.58 0.48],...
         'XGrid','on', 'YGrid','on',...
         'Tag','Axes1');
%
%  GUI heading text box.
%
HTbH=uicontrol('Style','text',...
               'Units','normalized',...
               'Position',[.425 .97 .3 .025],...
               'String','Maneuver Selection',...
               'FontSize',9,...
               'FontWeight','bold',...
               'FontAngle','italic');  
%
%  Listbox for fdata variables.
%
LbH=uicontrol('Style','listbox',...
               'Units','normalized',...
               'Position',[.01 .18 .2 .75],...
               'String',varlab,...
               'Value',4,...
               'Tag','Listbox1',...
               'Callback','cut_plot;');
%
%  Radiobutton for grid.
%
RbH=uicontrol('Style','radiobutton',...
              'Units','normalized',...
              'Position',[.85 .3 .075 .025],...
              'String','Grid',...
              'FontSize',8,...
              'Value',1,...
              'Callback','sid_grid;');
%
%  Pushbutton for moving back to the previous GUI screen.
%
PbH=uicontrol('Style','pushbutton',...
              'Units','normalized',...
              'Position',[.85 .2 .1 .04],...
              'String','<< Back',...
              'FontSize',9,...
              'FontWeight','bold',...
              'Callback','cut_back;');
%
%  Pushbutton for moving to the next GUI screen.
%
Pb2H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.85 .14 .1 .04],...
               'String','Next >>',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','cut_next;');
%
%  Pushbutton for closing the graphic display.
%
Pb3H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.85 .08 .1 .04],...
               'String','Close',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','sid_close;');
%
%  Text help for cut pushbutton.
%
TbH=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[.35 .09 .4 .12],...
              'BackgroundColor',[1,1,1],...
              'ForegroundColor',[1 0 .2],...
              'String',['                                    ';...
                        'Select initial time on the graph.   ';...   
                        'Use the right mouse button for      ';...
                        'manual input in the command window. ';...
                        '                                    '],...
              'FontSize',9,...
              'Tag','Text1',...
              'Visible','off');  
%
%  Pushbutton to cut the flight test maneuver.
%
Pb4H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.35 .3 .2 .04],...
               'String','Cut Maneuver',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','cut_cutftd;');
%
%  Pushbutton to undo the cut flight test maneuver.
%
Pb5H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.6 .3 .2 .04],...
               'String','Undo Cut',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','cut_undo;');
%
%  Pushbutton to reset the flight test maneuver.
%
Pb6H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.35 .24 .2 .04],...
               'String','Reset Maneuver',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','cut_reset;');
%
%  Initialize the fdata index limits.
%
if ~exist('indi')
  indi=1;
  indf=length(t);
  indil=indi;
  indfl=indf;
  indio=indi;
  indfo=indf;
end
%
%  Initialize the plot variables.
%
ixpltvar=1;
xpltlab=varlab(ixpltvar,:);
xpltvar=t(indi:indf);
iypltvar=get(LbH,'Value');
ypltlab=varlab(iypltvar,:);
ypltvar=fdata([indi:indf],iypltvar);
%
%  Strip any markers on the plot labels.
%
xpltlab(1)=' ';
ypltlab(1)=' ';
%
%  Plot command.
%
sid_plot(xpltvar,ypltvar,xpltlab,ypltlab);
return
