%
%  script sid_dcmp.m
%
%  Usage: sid_dcmp;
%
%  Description:
%
%    Creates GUI for data compatibility analysis 
%    using data from standard data matrix fdata.  
%    This routine contains all the code to set up the GUI.  
%
%  Input:
%
%    None
%
%  Output:
%
%    GUI
%

%
%    Calls:
%      dcmp_plot.m
%      dcmp_back.m
%      dcmp_resplot.m
%      dcmp_psel.m
%      dcmp_chk.m
%      dcmp_est.m
%      dcmp_cor.m
%      sid_grid.m
%      sid_close.m
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      22 Oct 2000 - Created and debugged, EAM.
%      28 Oct 2000 - Added general model structure capability, EAM.
%      30 Nov 2000 - Added data correction command, EAM.
%
%
%  Copyright (C) 2000  Eugene A. Morelli
%
%
%  This program carries no warranty, not even the implied 
%  warranty of merchantability or fitness for a particular purpose.  
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@larc.nasa.gov
%

%
%  GUI set up.
%
%
%  Figure window.
%
FgH=figure('Units','normalized',...
           'Position',[0.352 0.0437 0.64 0.88],...
           'Color',[0.8 0.8 0.8],...
           'Name','Aircraft System IDentification',...
           'NumberTitle','off',...
           'Tag','Fig1',...
           'ToolBar','none');
%
%  Axes for plotting.
%
Ax1H=axes('Box','on',...
          'Units','normalized',...
          'Position',[0.13 0.70 0.66 0.235],...
          'XGrid','on', 'YGrid','on',...
          'Tag','Axes1');
Ax2H=axes('Box','on',...
          'Units','normalized',...
          'Position',[0.13 0.39 0.66 0.235],...
          'XGrid','on', 'YGrid','on',...
          'Tag','Axes2');
Ax3H=axes('Box','on',...
          'Units','normalized',...
          'Position',[0.13 0.08 0.66 0.235],...
          'XGrid','on', 'YGrid','on',...
          'Tag','Axes3');
xlabel('Time (sec)');
%
%  GUI heading text box.
%
HTbH=uicontrol('Style','text',...
               'Units','normalized',...
               'Position',[.3 .97 .40 .03],...
               'String','Data Compatibility Analysis',...
               'FontSize',10,...
               'FontWeight','bold',...
               'FontAngle','italic');  
%
%  Text label for data compatibility kinematics popupmenu.
%
Tb1H=uicontrol('Style','text',...
               'Units','normalized',...
               'Position',[.845 .95 .1 .025],...
               'String','Kinematics',...
               'FontSize',8);  
%
%  Popupmenu for data compatibility kinematics.
%
Pu1H=uicontrol('Style','popupmenu',...
               'Units','normalized',...
               'Position',[.82 .90 .165 .04],...
               'String',{' Rotation  ';' Translation'},...
               'Value',1,...
               'Max',3,...
               'Tag','Popupmenu1',...
               'Callback','dcmp_plot;');
%
%  Radiobutton for grid.
%
RbH=uicontrol('Style','radiobutton',...
              'Units','normalized',...
              'Position',[.85 .72 .075 .025],...
              'String','Grid',...
              'FontSize',8,...
              'Value',1,...
              'Callback',['axes(Ax1H);sid_grid;',...
                          'axes(Ax2H);sid_grid;',...
                          'axes(Ax3H);sid_grid;']);
%
%  Pushbutton for moving to the previous GUI screen.
%
Pb1H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.84 .22 .12 .04],...
               'String','<< Back',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','dcmp_back;');
%
%  Pushbutton for moving to the next GUI screen.
%
%Pb2H=uicontrol('Style','pushbutton',...
%               'Units','normalized',...
%               'Position',[.84 .16 .12 .04],...
%               'String','Next >>',...
%               'FontSize',9,...
%               'FontWeight','bold',...
%               'Callback','dcmp_next;');
%
%  Pushbutton for closing the graphic display.
%
Pb3H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.84 .10 .12 .04],...
               'String','Close',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','sid_close;');
%
%  Pushbutton for plotting measured and model data.
%
Pb4H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.81 .78 .18 .04],...
               'String','Plot Residuals',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','dcmp_resplot;');
%
%  Pushbutton for editing the data compatibility dynamic model.
%
Pb5H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.82 .60 .16 .04],...
               'String','Edit Model',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','clear p0c ipc pclab ims imo cc; edit dcmp_psel.m');
%
%  Pushbutton for doing data compatibility check.
%
Pb6H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.82 .52 .16 .04],...
               'String','Check',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','dcmp_chk;');
%
%  Pushbutton for doing data compatibility 
%  instrumentation error parameter estimation.
%
Pb7H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.81 .44 .18 .04],...
               'String','Estimate Errors',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','dcmp_est;');
%
%  Pushbutton for applying instrumentation error corrections.
%
Pb8H=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[.81 .36 .18 .04],...
               'String','Correct Data',...
               'FontSize',9,...
               'FontWeight','bold',...
               'Callback','dcmp_cor;');
%
%  Initialize data compatibility model outputs.
%
dcmp_chk;
return
